# Site Settings
title: Robert Michael Pyne
description: CV and Portfolio
author: Robert Michael Pyne
theme: jekyll-theme-minimal # A clean, professional look

# Contact Information (Optional, but shows up in some themes)
email: robertmichaelpyne@gmail.com
linkedin_username: robert-pyne-5300aa49
github_username: robertmpyne

# Author information
author:
  name: "Your Name"
  avatar: "/home/robertpyne/Documents/Github/profile_pic.png"  # Path to your uploaded image
  bio: "ML Engineer | Molecular Biology"
  
# Build Settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # Allows you to use themes easily
  - jekyll-seo-tag     # Helps your CV show up better in search results

# Markdown Settings
markdown: kramdown
highlighter: rouge # For clean code-snippet highlighting
